### ISSUE TITLE
Micropython aht20-test example is broken

### ISSUE THREAD

**Issue by jtiscione** [andypiper/fivebyfive#10]
Running the aht20-test script on this 5x5 board with MicroPython 1.20.0 generates

Traceback (most recent call last):
  File "<stdin>", line 12, in <module>
  File "/lib/ahtx0.py", line 47, in __init__
  File "/lib/ahtx0.py", line 56, in reset
OSError: [Errno 116] ETIMEDOUT

This gets printed immediately as soon as the script tries to create the sensor by calling ahtx0.AHT20(i2c) so this might be a bug in ahtx0.

**Comment by andypiper** [comment]
Thanks for the report - I’m a bit busy at the moment, but I’ll try to take a look in the next couple of weeks. Based on the symptom it definitely reads like a driver issue.
